[project]
name = "poopyrus-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.2",
    "motor>=3.6.0",
    "pydantic-settings>=2.6.0",
    "pymongo>=4.9.1",
    "python-dotenv>=1.0.1",
]
