apiVersion: v1
kind: Service
metadata:
    name: poopyrus-api-svc
    labels:
        app: poopyrus-api
    annotations:
        cloud.google.com/backend-config: '{"default": "homy-backendconfig"}'
spec:
    ports:
        - name: http
          port: 8080
          protocol: TCP
          targetPort: 8080
    selector:
        app: poopyrus-api
